# Generated by Django 2.2.6 on 2019-10-10 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
