# Generated by Django 2.2.6 on 2019-10-10 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('damages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='damage',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='damage',
            name='phone',
            field=models.CharField(default=-5555, max_length=20),
            preserve_default=False,
        ),
    ]
